added fee deficit metric
chainflip-io/chainflip-prometheus-exporter pull request #31
Opened 2024-01-19 12:36 UTC by marcellorigotti

Adde metric to track the fee deficit of the network, currently it has been added only for dot and eth since for btc is not trivial to get this info (when Martin is back will talk to him on how it can be done for btc)

2024-01-19 12:42 UTC, tomjohnburton requested changes

2024-01-19 12:42 UTC, tomjohnburton commented on src/metrics/chainflip/gaugeFeeDeficit.ts
> +        metric.labels('Ethereum').set(deficitEth);
```suggestion
        metric.labels('ethereum').set(deficitEth);
```

2024-01-19 12:42 UTC, tomjohnburton commented on src/metrics/chainflip/gaugeFeeDeficit.ts
> +        metric.labels('Polkadot').set(deficitDot);
```suggestion
        metric.labels('polkadot').set(deficitDot);
```

2024-01-19 12:50 UTC, marcellorigotti commented on src/metrics/chainflip/gaugeFeeDeficit.ts
> +    labelNames: ['chain'],
tracked_chain seems perfect!

2024-01-26 10:27 UTC, tomjohnburton approved these changes

2024-01-26 10:39 UTC, merged